name: Déploiement de l'API de Recommandation

# --- Déclencheurs du Workflow ---
on:
  # 1. Permet de lancer ce workflow manuellement depuis l'onglet "Actions" de GitHub
  workflow_dispatch:

# --- Définition des Tâches (Jobs) ---
jobs:
  # --- Tâche de Conteneurisation et Déploiement de l'API ---
  build-and-deploy-api:
    runs-on: ubuntu-latest
    steps:
      # Étape 1: Récupère le code de votre dépôt
      - name: Checkout du code
        uses: actions/checkout@v4

      # Étape 2: Connexion à Azure
      # Utilise les identifiants de votre principal de service stockés dans les secrets GitHub
      - name: Connexion à Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Étape 3: Connexion à Azure Container Registry (ACR)
      # Assurez-vous que votre principal de service a les droits pour pousser des images sur ce registre
      - name: Connexion à Azure Container Registry
        run: az acr login --name monregistreacr
        # Remplacez 'monregistreacr' par le nom de votre registre de conteneurs Azure

      # Étape 4: Construction et push de l'image Docker
      # Cette étape suppose que vous avez un Dockerfile à la racine de votre projet
      - name: Construction et push de l'image Docker de l'API
        run: |
          az acr build \
            --registry monregistreacr \
            --image api/recommandation-api:latest \
            .
        # Remplacez 'monregistreacr' par le nom de votre registre
        # 'api/recommandation-api:latest' est le nom et le tag de votre image

      # Étape 4.5: Configuration des variables d'environnement sur App Service
      - name: Définition des paramètres de l'application
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp config appsettings set \
              --resource-group <NOM_DE_VOTRE_GROUPE_DE_RESSOURCES> \
              --name mon-api-app-service \
              --settings "AZURE_CONNECTION_STRING=${{ secrets.AZURE_CONNECTION_STRING }}" "ANOTHER_VAR=some_value"
            # Remplacez <NOM_DE_VOTRE_GROUPE_DE_RESSOURCES> par le nom correct.

      # Étape 5: Déploiement sur Azure App Service
      # Met à jour votre App Service pour utiliser la nouvelle image Docker
      - name: Déploiement sur Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'mon-api-app-service' # Remplacez par le nom de votre App Service
          images: 'monregistreacr.azurecr.io/api/recommandation-api:latest' # Chemin complet de votre image

      # Étape 6: Déconnexion d'Azure
      - name: Déconnexion d'Azure
        run: az logout